// generated by gen_get_by_guid.go

package ccv2

import (
  "code.cloudfoundry.org/cli/api/cloudcontroller"
  "code.cloudfoundry.org/cli/api/cloudcontroller/ccv2/internal"
)

// GetOrganization returns the Organization associated with the provided GUID.
func (client *Client) GetOrganization(guid string) (Organization, Warnings, error) {
	request, err := client.newHTTPRequest(requestOptions{
		RequestName: internal.GetOrganizationRequest,
		URIParams:   Params{"organization_guid": guid},
	})
	if err != nil {
		return Organization{}, nil, err
	}

	var organization Organization
	response := cloudcontroller.Response{
		Result: &organization,
	}

	err = client.connection.Make(request, &response)
	return organization, response.Warnings, err
}
